#!/bin/bash
echo "Old .dotfiles moved to .file.old";

INSTALLDIR=${1:-$HOME}

for i in .bash  .bash_logout  .bashrc  bin  completion .tmux.conf .tmux-powerlinerc .screenrc .inputrc .ssh/config
do
	#echo moving $INSTALLDIR/$i to $INSTALLDIR/$i.old 2> /dev/null
	mv $INSTALLDIR/$i $INSTALLDIR/$i.old 
	ln -s -f $PWD/$i $INSTALLDIR/$i;
done;

echo  "Do you want to use my vim configs? [Y/n]"
read -n 1 use_vim_configs

if [ "$use_vim_configs" != "n" ]; then
	test -d $INSTALLDIR/.vim && rm -rf $INSTALLDIR/.vim
	ln -s -f $PWD/.vim $INSTALLDIR/.vim
	ln -s -f $PWD/.vimrc $INSTALLDIR/.vimrc
fi
echo


echo "Git config settings"
git_name="Sergey Epishkin"
echo  "Name: $name"
git_email="sergey.epishkin@lazada.com"
echo  "Email: $git_email"

cp $PWD/.gitconfig $INSTALLDIR/.gitconfig
sed -i.old "s/%%GITNAME%%/$git_name/" $INSTALLDIR/.gitconfig
sed -i.old "s/%%GITEMAIL%%/$git_email/" $INSTALLDIR/.gitconfig

if [ ! -d $INSTALLDIR/.node-completion ]; then
	mkdir $INSTALLDIR/.node-completion
fi

if [ ! -d $HOME/repos ]; then
	mkdir $HOME/repos
fi

if [ ! -d $HOME/repos/tmux-powerline ]; then
	git clone git://github.com/erikw/tmux-powerline.git $HOME/repos/tmux-powerline
fi

echo "Initializing submodules..."
git submodule init && git submodule update
