#!/bin/bash

INSTALLDIR=${1:-$HOME}
BACKUP_DIR=${1:-$HOME}/.dot_bk

echo "Old .dotfiles moved to $BACKUP_DIR"
rm -rfv $BACKUP_DIR; mkdir -p $BACKUP_DIR
for i in .bash .bash_logout .bashrc bin completion .gitconfig .tmux.conf .tmux-powerlinerc .screenrc .inputrc .ssh/config
do
	mv -v $INSTALLDIR/$i $BACKUP_DIR/
	ln -sv -f $PWD/$i $INSTALLDIR/$i;
done;

echo  "Do you want to change git author settings? [Y/n]"
read -n 1 retval; echo
if [ "$retval" != "n" ]; then
    echo "user.name:"
    read -e git_name
    git config --global user.name "$git_name"
    echo  "user.email:"
    read -e git_email
    echo  "Email: $git_email"
    git config --global user.email $git_email

    # keeping this repository author
    echo "Setting this repos author settings: $git_name <$git_email>"
    git_email="sergey.epishkin@lazada.com"
    git_name="Serge Epishan"
    git config  user.name "$git_name"
    git config  user.email $git_email

fi

echo  "Do you want to use my vim configs? [Y/n]"
read -n 1 use_vim_configs

if [ "$use_vim_configs" != "n" ]; then
	test -d $INSTALLDIR/.vim && rm -rf $INSTALLDIR/.vim
	ln -s -f $PWD/.vim $INSTALLDIR/.vim
	ln -s -f $PWD/.vimrc $INSTALLDIR/.vimrc
fi
echo


if [ ! -d $INSTALLDIR/.node-completion ]; then
	mkdir $INSTALLDIR/.node-completion
fi

if [ ! -d $HOME/repos ]; then
	mkdir $HOME/repos
fi

if [ ! -d $HOME/repos/tmux-powerline ]; then
	git clone git://github.com/erikw/tmux-powerline.git $HOME/repos/tmux-powerline
fi

echo "Initializing submodules..."
git submodule init && git submodule update
